Hard Limit in Config (for Pagination)
yajra/laravel-datatables pull request #2494
Opened 2020-10-25 09:23 UTC by saaiful

https://github.com/yajra/laravel-datatables/issues/2493

2020-10-31 02:28 UTC, yajra requested changes

2020-10-31 02:28 UTC, yajra commented on src/config/datatables.php
> +     * Maximum record per page
I think the correct word is records?

`Maximum records per page.`

2020-10-31 02:30 UTC, yajra commented
PR looks good aside from the minor typo? Will test this today on actual project. Thanks!

2020-10-31 02:36 UTC, yajra commented
Also, maybe we can also include `records_per_page` on the config while we're at it instead of hard coding it at 10?

2020-10-31 02:43 UTC, yajra commented
Just tested this and it breaks the dataTables info? Tried setting the max records to 3 and the requested length is 10.

![image](https://user-images.githubusercontent.com/2687997/97769419-c1ae3b00-1b65-11eb-9150-6ee73ee5fb3b.png)

Expected info should be something like  `Showing 1 to 3 of 10 results` or I might be missing something?

2020-11-01 15:15 UTC, saaiful commented
> Just tested this and it breaks the dataTables info? Tried setting the max records to 3 and the requested length is 10.
> 
> ![image](https://user-images.githubusercontent.com/2687997/97769419-c1ae3b00-1b65-11eb-9150-6ee73ee5fb3b.png)
> 
> Expected info should be something like `Showing 1 to 3 of 10 results` or I might be missing something?

I will try to fix that.

2021-01-15 09:11 UTC, saaiful commented
I just solved the issue.
In Yajra\DataTables\Html\Builder
```/**
     * Generate DataTables js parameters.
     *
     * @param  array $attributes
     * @return string
     */
    public function parameterize($attributes = [])
    {
        $parameters = (new Parameters($attributes))->toArray();

        $max_record_per_page = $this->config->get('datatables.max_record_per_page', 0);
        if (!array_key_exists('lengthMenu', $parameters)) {
            $parameters['lengthMenu'] = [10, 25, 50, 100];
        }

        if ($max_record_per_page != 0) {
            $lengthMenu = array_unique($parameters['lengthMenu']);
            foreach ($lengthMenu as $key => $value) {
                if ($value > $max_record_per_page) {
                    unset($lengthMenu[$key]);
                }
            }
            $lengthMenu = array_values($lengthMenu);
            if (empty($lengthMenu)) {$lengthMenu = [$max_record_per_page];}
            sort($lengthMenu);
            $parameters['lengthMenu'] = $lengthMenu;
        }

        $values = [];
        $replacements = [];

        foreach (Arr::dot($parameters) as $key => $value) {
            if ($this->isCallbackFunction($value, $key)) {
                $values[] = trim($value);
                Arr::set($parameters, $key, '%' . $key . '%');
                $replacements[] = '"%' . $key . '%"';
            }
        }

        $new = [];
        foreach ($parameters as $key => $value) {
            Arr::set($new, $key, $value);
        }

        $json = json_encode($new);

        $json = str_replace($replacements, $values, $json);

        return $json;
    }
```

This will insert `lengthMenu` parameter according to `max_record_per_page` in config file. This will not affect manual `lengthMenu` insertion in "builder parameters".

2021-01-16 12:40 UTC, closed without merging