dont add BelongsToMany relation column to select
yajra/laravel-datatables pull request #2721
Opened 2021-12-29 09:20 UTC by affaron

It seems like a part of "duplicate column" problems with sorting/filtering by BelongsToMany relation column are coming from this. 

When you have same column names in your main and relation tables adding a `->select()` is not helping because the relation column is still added in joinEagerLoadedColumn(). And depending on the situation either your main model column will be populated with same name relation column or you're getting an error in your aggregate queries. Example:
```
Exception Message:

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'name' (SQL: select count(*) as aggregate from (select `crm_companies`.`id`, `crm_companies`.`name`, `dic_company_types`.`name` from `crm_companies` left join `crm_company_types` on `crm_company_types`.`company_id` = `crm_companies`.`id` left join `dic_company_types` on `crm_company_types`.`type_id` = `dic_company_types`.`id` where LOWER(`dic_company_types`.`name`) LIKE %clearing agent% group by `crm_companies`.`name`) count_row_table)
```
(`crm_companies`.`name` is the main model column, `dic_company_types`.`name`  - automatically added relation column and hence the conflict)

So I look into the code and found this place. `$this->performJoin($table, $foreign, $other);` looks unnecessary since it's performed anyway after the switch block and `addSelect` is adding a relation column that doesn't seem to be required and causes duplicates. Please correct me if I'm wrong.

Thanks

2022-02-01 10:10 UTC, yajra commented
Per @dragonfly4 [feedback](https://github.com/yajra/laravel-datatables/issues/2705#issuecomment-1026604604), PR doesn't fixed the issue.

> I tested that but it's not fixing the issue above. Same error.

2022-02-01 10:15 UTC, yajra commented
I just recalled that sorting on belongsToMany would indeed yield to a duplicate records even when executed on the SQL level.

If you guys can provide a raw SQL on how to implement it, I will try to convert it on the package level.

2022-07-01 09:15 UTC, yajra requested changes

2022-07-01 09:15 UTC, yajra commented on src/DataTables.php
> +
Please revert this change

2022-07-01 09:15 UTC, yajra commented on src/DataTables.php
> +    /**
Please revert this too, already removed on v10

2022-09-23 10:28 UTC, affaron commented
Hey, sorry, didn't have time to get back to this. I reverted those changes from a merge I did into this branch back then. Didn't realise that it'd affect this request.

Anyway, it still seems that adding that addSelect (even the recent one in HasOneThrough case) causes some column names duplicating when you sort/search (if you already have select attached before). Maybe it's best to remove them and suggest users to use selects (it was already suggested as I recall). 

I'll try to look into this issue again later.

2023-01-31 12:39 UTC, turdakhov commented
I solved it this way: 
return $this->belongsToMany(Characteristic::class)-**>distinct()**->with('values');

2025-05-16 04:36 UTC, Seb33300 commented
I think this issue is already fixed by https://github.com/yajra/laravel-datatables/pull/3238

2025-05-17 03:43 UTC, closed without merging