Optimize simple queries
yajra/laravel-datatables pull request #3135
Opened 2024-04-12 14:01 UTC by Arkhas

The issues was for simple queries with complexe wheres, a sub query was used resulting in the following query : 

```sql
select count(*)
from (select "users".*
      from "users"
      where (select "title"
             from "posts"
             where "posts"."user_id" = "users"."id"
             order by "created_at" asc
    ) = ?
) count_row_table
```
resulting into an uneccessary temporary table, the query we would like to have would be this one : 

```sql
select count(*)
from "users"
where (select "title"
       from "posts"
       where "posts"."user_id" = "users"."id"
       order by "created_at" asc
) = ?
```

2024-04-13 02:40 UTC, yajra commented
I guess this PR also fixes #3133. @abdulrhmansouda would you be able to review? Thanks!

2024-04-13 08:43 UTC, abdulrhmansouda commented
I fixed this problem when I changed the isComplexQuery function #3133.
and it's ready. you can review it.

2024-04-13 12:06 UTC, yajra commented
Please run `composer pr` on your local machine to fix the linting. I haven't figured out yet how to automate in PR. Thanks!

2024-04-13 12:21 UTC, yajra requested changes
The changes look good so far. 

Please fix the code style using `composer pint` or `composer pr` to run all quality tools. It will make the PR easier to review.

Thanks!

2024-04-13 12:21 UTC, yajra commented on src/QueryDataTable.php
>          $builder->select($this->getConnection()->raw("'1' as {$row_count}"));
Maybe we can consider @abdulrhmansouda suggestion of removing the orders?

```suggestion
        $builder->select($this->getConnection()->raw("'1' as {$row_count}"))->reorder();
```

2024-04-16 04:54 UTC, yajra approved these changes

2024-04-16 04:54 UTC, merged

2024-04-16 05:00 UTC, yajra commented
Released on v11.1.0, 🚀 thanks!